//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaimandOrder
    {
        public long MemberNumber { get; set; }
        public string dOrderGuid { get; set; }
        public string Account { get; set; }
        public string dReceiver { get; set; }
        public string dEmail { get; set; }
        public string dAddress { get; set; }
        public System.DateTime dDate { get; set; }
    }
}
