//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpacepingpongDatabaseEntities : DbContext
    {
        public SpacepingpongDatabaseEntities()
            : base("name=SpacepingpongDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DaimandOrder> DaimandOrders { get; set; }
        public virtual DbSet<DaimandOrderDetail> DaimandOrderDetails { get; set; }
        public virtual DbSet<DaimandStore> DaimandStores { get; set; }
        public virtual DbSet<FaceRecognization> FaceRecognizations { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<PlayList> PlayLists { get; set; }
        public virtual DbSet<PointOrder> PointOrders { get; set; }
        public virtual DbSet<PointShoppingCart> PointShoppingCarts { get; set; }
        public virtual DbSet<PointStore> PointStores { get; set; }
    }
}
